"""
Self-healing: use Gemini to patch vulnerable code and open a GitHub PR.
Uses Redis leader election to ensure only one control-plane replica does this.
"""
import asyncio
import logging
import socket
import uuid
import google.generativeai as genai
from shared.config.settings import settings
from shared.redis_client import get_redis
from shared.db.crud import update_incident_pr
from control_plane.healing.github_client import (
    get_repo, get_default_branch, create_branch, commit_file, create_pull_request
)
from control_plane.healing.repo_scanner import find_candidate_files

logger = logging.getLogger(__name__)

LEADER_KEY = "cognithhorn:healing-leader"
LEADER_TTL = 60  # seconds
MY_ID = socket.gethostname()


async def _acquire_leader_lock() -> bool:
    """Try to acquire the self-healing leader lock. Returns True if acquired."""
    redis = get_redis()
    result = await redis.set(LEADER_KEY, MY_ID, nx=True, ex=LEADER_TTL)
    return result is True


async def run_self_healing(incident: dict) -> None:
    """Entry point for self-healing. Runs as a background task."""
    if not settings.enable_self_healing:
        logger.info("Self-healing disabled, skipping incident %s", incident.get("id"))
        return

    if not await _acquire_leader_lock():
        logger.info("Not the healing leader, skipping incident %s", incident.get("id"))
        return

    try:
        attack_type = incident.get("attack_type", "unknown")
        affected_param = incident.get("affected_parameter")
        incident_id = incident.get("id")

        # Find candidate files
        candidates = await asyncio.to_thread(find_candidate_files, attack_type, affected_param)
        if not candidates:
            logger.warning("No candidate files found for incident %s", incident_id)
            return

        # Generate patch for the first candidate
        candidate = candidates[0]
        patched_content, pr_description = await _generate_patch(
            candidate["content"], attack_type, affected_param, incident
        )
        if not patched_content:
            return

        # Create branch and PR
        pr_url = await asyncio.to_thread(
            _create_pr,
            candidate["path"],
            patched_content,
            pr_description,
            incident_id,
            attack_type,
        )
        if pr_url and incident_id:
            await update_incident_pr(incident_id, pr_url)
            logger.info("Self-healing PR created: %s", pr_url)

    except Exception as e:
        logger.error("Self-healing failed for incident %s: %s", incident.get("id"), e, exc_info=True)


async def _generate_patch(
    file_content: str, attack_type: str, affected_param: str | None, incident: dict
) -> tuple[str, str]:
    """Ask Gemini to patch the file. Returns (patched_content, pr_description)."""
    try:
        genai.configure(api_key=settings.gemini_api_key)
        model = genai.GenerativeModel("gemini-1.5-flash")
        prompt = (
            f"You are a security engineer. The following code has a {attack_type} vulnerability"
            + (f" in the '{affected_param}' parameter" if affected_param else "")
            + f".\n\nExplanation: {incident.get('explanation', '')}\n\n"
            f"Provide ONLY the complete corrected file contents with no markdown, no explanation.\n"
            f"Then on the LAST LINE write: PR_DESCRIPTION: <one sentence>\n\n"
            f"VULNERABLE FILE:\n{file_content[:8000]}"
        )
        response = await asyncio.to_thread(model.generate_content, prompt)
        text = response.text.strip()
        pr_desc = ""
        if "PR_DESCRIPTION:" in text:
            parts = text.rsplit("PR_DESCRIPTION:", 1)
            patched = parts[0].strip()
            pr_desc = parts[1].strip()
        else:
            patched = text
            pr_desc = f"Fix {attack_type} vulnerability"
        return patched, pr_desc
    except Exception as e:
        logger.error("Gemini patch generation failed: %s", e)
        return "", ""


def _create_pr(
    file_path: str, content: str, description: str, incident_id, attack_type: str
) -> str:
    repo = get_repo()
    base = get_default_branch(repo)
    branch_name = f"cognithhorn/fix-{attack_type}-{incident_id or uuid.uuid4().hex[:8]}"
    create_branch(repo, branch_name, base)
    commit_file(
        repo, branch_name, file_path, content,
        f"fix: remediate {attack_type} vulnerability (CogniThorn auto-patch)"
    )
    return create_pull_request(
        repo,
        title=f"[CogniThorn] Fix {attack_type} vulnerability",
        body=f"{description}\n\nAuto-generated by CogniThorn Self-Healing.\nIncident ID: {incident_id}",
        head=branch_name,
        base=base,
    )
